"use client";
import { useEffect, useMemo, useState } from "react";
import { Plus, Copy, Check, Trash2 } from "lucide-react";
import config from "../../../config.json";
import TabContainer from "../shared/TabContainer";
import TabHeader from "../shared/TabHeader";
import EmptyState from "../shared/EmptyState";

type DraftStatus = "draft" | "scheduled" | "posted";

type Draft = {
  id: string;
  hook: string;
  caption: string;
  trigger_word: string | null;
  slide_count: number;
  type: "carousel" | "reel" | "image" | "story";
  status: DraftStatus;
  scheduled_for: string | null;
  posted_at: string | null;
  created_at: string;
  updated_at: string;
};

type NewDraft = Omit<Draft, "id" | "created_at" | "updated_at" | "posted_at" | "scheduled_for">;

const TYPE_OPTIONS: Draft["type"][] = ["carousel", "reel", "image", "story"];

const emptyDraft = (): NewDraft => ({
  hook: "",
  caption: "",
  trigger_word: (config.triggerWords?.[0] as string) ?? null,
  slide_count: 1,
  type: "carousel",
  status: "draft",
});

/**
 * Drafts tab.
 *
 * Caption writer + status board.
 *  - Status flow: draft -> scheduled -> posted
 *  - Trigger word picker (drives lead-magnet tracking on IG)
 *  - Slide count (for carousels)
 *
 * Drafts can be written by hand here, or generated by Claude Code via
 * /prompts/5-draft-caption.md and /prompts/9-build-content-week.md.
 */
export default function Drafts() {
  const [drafts, setDrafts] = useState<Draft[]>([]);
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [statusFilter, setStatusFilter] = useState<"all" | DraftStatus>("draft");

  const [addOpen, setAddOpen] = useState(false);
  const [draft, setDraft] = useState<NewDraft>(emptyDraft());

  const [copiedId, setCopiedId] = useState<string | null>(null);

  const load = () => {
    setLoading(true);
    fetch("/api/data?tab=drafts")
      .then((r) => r.json())
      .then((r) => {
        setDrafts(r.data ?? []);
        setLoading(false);
      })
      .catch(() => setLoading(false));
  };

  useEffect(load, []);

  async function createDraft() {
    if (!draft.caption.trim()) return;
    setSaving(true);
    try {
      const res = await fetch("/api/data?tab=drafts", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(draft),
      });
      if (res.ok) {
        setDraft(emptyDraft());
        setAddOpen(false);
        load();
      }
    } finally {
      setSaving(false);
    }
  }

  async function patchDraft(id: string, patch: Partial<Draft>) {
    setSaving(true);
    try {
      const res = await fetch("/api/data?tab=drafts", {
        method: "PATCH",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ id, ...patch }),
      });
      if (res.ok) load();
    } finally {
      setSaving(false);
    }
  }

  async function deleteDraft(id: string) {
    if (!confirm("Delete this draft?")) return;
    setSaving(true);
    try {
      const res = await fetch(`/api/data?tab=drafts&id=${id}`, { method: "DELETE" });
      if (res.ok) load();
    } finally {
      setSaving(false);
    }
  }

  function copyCaption(d: Draft) {
    if (!navigator.clipboard) return;
    navigator.clipboard.writeText(d.caption).then(() => {
      setCopiedId(d.id);
      setTimeout(() => setCopiedId(null), 1500);
    });
  }

  const counts = useMemo(
    () => ({
      draft: drafts.filter((d) => d.status === "draft").length,
      scheduled: drafts.filter((d) => d.status === "scheduled").length,
      posted: drafts.filter((d) => d.status === "posted").length,
    }),
    [drafts]
  );

  const visible = statusFilter === "all" ? drafts : drafts.filter((d) => d.status === statusFilter);
  const triggers = config.triggerWords ?? [];

  return (
    <TabContainer>
      <TabHeader
        title="Drafts"
        subtitle="Write captions in your voice. Tag with trigger words, set slide count, move them from draft to scheduled to posted."
        onScrapeComplete={load}
      />

      {/* Status filters + add button */}
      <div
        style={{
          display: "flex",
          justifyContent: "space-between",
          alignItems: "center",
          flexWrap: "wrap",
          gap: "0.6rem",
          marginBottom: "1.5rem",
        }}
      >
        <div style={{ display: "flex", gap: "0.35rem", flexWrap: "wrap" }}>
          {(["draft", "scheduled", "posted", "all"] as const).map((s) => {
            const active = statusFilter === s;
            const count = s === "all" ? drafts.length : counts[s];
            return (
              <button
                key={s}
                onClick={() => setStatusFilter(s)}
                style={{
                  background: active ? "var(--color-burgundy)" : "var(--color-cream)",
                  border: "none",
                  color: active ? "#fff" : "var(--color-text-dim)",
                  padding: "0.4rem 0.95rem",
                  borderRadius: "20px",
                  fontSize: "0.75rem",
                  cursor: "pointer",
                  fontFamily: "var(--font-body)",
                  fontWeight: 600,
                }}
              >
                {s === "all" ? `All (${count})` : `${cap(s)} (${count})`}
              </button>
            );
          })}
        </div>
        <button
          onClick={() => {
            if (addOpen) setAddOpen(false);
            else {
              setDraft(emptyDraft());
              setAddOpen(true);
            }
          }}
          style={{
            background: "var(--color-burgundy)",
            border: "none",
            color: "#fff",
            padding: "0.55rem 1.1rem",
            borderRadius: "10px",
            fontSize: "0.82rem",
            cursor: "pointer",
            fontFamily: "var(--font-body)",
            fontWeight: 600,
            display: "inline-flex",
            alignItems: "center",
            gap: "0.4rem",
          }}
        >
          <Plus size={14} strokeWidth={2.2} />
          {addOpen ? "Close" : "New draft"}
        </button>
      </div>

      {/* Add form */}
      {addOpen && (
        <div
          style={{
            background: "#fff",
            border: "1px solid var(--color-burgundy)",
            borderRadius: "14px",
            padding: "1.25rem 1.5rem",
            marginBottom: "1.5rem",
            boxShadow: "var(--shadow-sm)",
          }}
        >
          <p
            style={{
              fontSize: "0.7rem",
              color: "var(--color-text-dim)",
              letterSpacing: "0.1em",
              textTransform: "uppercase",
              marginBottom: "0.85rem",
              fontWeight: 700,
            }}
          >
            New draft
          </p>

          <input
            type="text"
            value={draft.hook}
            onChange={(e) => setDraft({ ...draft, hook: e.target.value })}
            placeholder="Hook (first line, the thing that stops the scroll)"
            style={inputStyle}
          />

          <textarea
            value={draft.caption}
            onChange={(e) => setDraft({ ...draft, caption: e.target.value })}
            placeholder="Caption body. Write the scene, not a label."
            rows={6}
            style={{ ...inputStyle, resize: "vertical", marginTop: "0.5rem" }}
          />

          <div
            style={{
              display: "flex",
              gap: "0.5rem",
              marginTop: "0.75rem",
              flexWrap: "wrap",
              alignItems: "center",
            }}
          >
            <select
              value={draft.type}
              onChange={(e) => setDraft({ ...draft, type: e.target.value as Draft["type"] })}
              style={selectStyle}
            >
              {TYPE_OPTIONS.map((t) => (
                <option key={t} value={t}>
                  {cap(t)}
                </option>
              ))}
            </select>

            <select
              value={draft.slide_count}
              onChange={(e) => setDraft({ ...draft, slide_count: Number(e.target.value) })}
              style={selectStyle}
            >
              {[1, 2, 3, 4, 5, 6, 7, 8, 9, 10].map((n) => (
                <option key={n} value={n}>
                  {n} slide{n > 1 ? "s" : ""}
                </option>
              ))}
            </select>

            <select
              value={draft.trigger_word ?? ""}
              onChange={(e) => setDraft({ ...draft, trigger_word: e.target.value || null })}
              style={selectStyle}
            >
              <option value="">No trigger word</option>
              {triggers.map((t) => (
                <option key={t} value={t}>
                  {t}
                </option>
              ))}
            </select>
          </div>

          <div style={{ display: "flex", gap: "0.5rem", marginTop: "1rem" }}>
            <button
              onClick={createDraft}
              disabled={saving || !draft.caption.trim()}
              style={{
                background: "var(--color-burgundy)",
                border: "none",
                color: "#fff",
                padding: "0.55rem 1.1rem",
                borderRadius: "8px",
                fontSize: "0.82rem",
                cursor: "pointer",
                fontFamily: "var(--font-body)",
                fontWeight: 600,
                opacity: saving || !draft.caption.trim() ? 0.6 : 1,
              }}
            >
              {saving ? "Saving..." : "Save draft"}
            </button>
            <button onClick={() => setAddOpen(false)} style={ghostBtn}>
              Cancel
            </button>
          </div>
        </div>
      )}

      {loading && (
        <div className="stagger" style={{ display: "flex", flexDirection: "column", gap: "0.6rem" }}>
          {[0, 1, 2].map((i) => (
            <div key={i} className="skeleton" style={{ height: "110px" }} />
          ))}
        </div>
      )}

      {!loading && drafts.length === 0 && (
        <EmptyState
          title="No drafts yet"
          body="Write your first caption here, or have Claude Code draft one for you using the caption prompt. It learns from your voice rules and top hooks."
          promptFile="5-draft-caption.md"
          actionLabel="Write one now"
          onAction={() => {
            setDraft(emptyDraft());
            setAddOpen(true);
          }}
        />
      )}

      {!loading && drafts.length > 0 && visible.length === 0 && (
        <div
          style={{
            background: "var(--color-cream)",
            border: "1px dashed var(--color-border)",
            borderRadius: "10px",
            padding: "1.5rem",
            textAlign: "center",
            fontSize: "0.85rem",
            color: "var(--color-text-dim)",
          }}
        >
          Nothing in {statusFilter}. Switch filter to see other drafts.
        </div>
      )}

      <div style={{ display: "flex", flexDirection: "column", gap: "0.75rem" }}>
        {visible.map((d) => (
          <div
            key={d.id}
            style={{
              background: "#fff",
              border: "1px solid var(--color-border)",
              borderRadius: "12px",
              padding: "1rem 1.25rem",
              boxShadow: "var(--shadow-sm)",
              opacity: d.status === "posted" ? 0.72 : 1,
            }}
          >
            <div style={{ display: "flex", gap: "0.4rem", marginBottom: "0.5rem", flexWrap: "wrap", alignItems: "center" }}>
              <StatusPill status={d.status} />
              <Tag>{d.type}</Tag>
              <Tag tone="dim">
                {d.slide_count} slide{d.slide_count > 1 ? "s" : ""}
              </Tag>
              {d.trigger_word && <Tag tone="burgundy">{d.trigger_word}</Tag>}
            </div>

            {d.hook && (
              <p style={{ fontFamily: "var(--font-header)", fontSize: "1.05rem", marginBottom: "0.45rem", lineHeight: 1.35 }}>
                {d.hook}
              </p>
            )}
            <p
              style={{
                fontSize: "0.86rem",
                lineHeight: 1.55,
                whiteSpace: "pre-wrap",
                color: "var(--color-text)",
                marginBottom: "0.85rem",
              }}
            >
              {d.caption}
            </p>

            <div style={{ display: "flex", gap: "0.5rem", flexWrap: "wrap", alignItems: "center" }}>
              {d.status === "draft" && (
                <button onClick={() => patchDraft(d.id, { status: "scheduled" })} style={primaryBtn} disabled={saving}>
                  Schedule
                </button>
              )}
              {d.status === "scheduled" && (
                <>
                  <button
                    onClick={() => patchDraft(d.id, { status: "posted" })}
                    style={primaryBtn}
                    disabled={saving}
                  >
                    <Check size={13} strokeWidth={2.2} style={{ marginRight: "0.3rem" }} />
                    Mark posted
                  </button>
                  <button onClick={() => patchDraft(d.id, { status: "draft" })} style={ghostBtn}>
                    Back to draft
                  </button>
                </>
              )}
              {d.status === "posted" && (
                <button onClick={() => patchDraft(d.id, { status: "draft" })} style={ghostBtn}>
                  Reopen
                </button>
              )}
              <button onClick={() => copyCaption(d)} style={ghostBtn}>
                <Copy size={12} strokeWidth={1.8} style={{ marginRight: "0.3rem" }} />
                {copiedId === d.id ? "Copied!" : "Copy"}
              </button>
              <button
                onClick={() => deleteDraft(d.id)}
                style={{ ...ghostBtn, color: "var(--color-burgundy)", marginLeft: "auto" }}
                aria-label="Delete draft"
                disabled={saving}
              >
                <Trash2 size={12} strokeWidth={1.8} />
              </button>
            </div>
          </div>
        ))}
      </div>

      {drafts.length > 0 && (
        <p
          style={{
            marginTop: "2rem",
            fontSize: "0.72rem",
            color: "var(--color-text-dim)",
            textAlign: "center",
          }}
        >
          Want Claude Code to draft a week of captions at once? Run{" "}
          <code style={{ fontFamily: "monospace", color: "var(--color-burgundy)" }}>
            /prompts/9-build-content-week.md
          </code>
          .
        </p>
      )}
    </TabContainer>
  );
}

function cap(s: string) {
  return s.charAt(0).toUpperCase() + s.slice(1);
}

const inputStyle: React.CSSProperties = {
  width: "100%",
  padding: "0.7rem 0.95rem",
  border: "1px solid var(--color-border)",
  borderRadius: "8px",
  fontSize: "0.88rem",
  fontFamily: "var(--font-body)",
  background: "#fff",
  color: "var(--color-text)",
  boxSizing: "border-box",
  outline: "none",
};

const selectStyle: React.CSSProperties = {
  padding: "0.5rem 0.85rem",
  border: "1px solid var(--color-border)",
  borderRadius: "8px",
  fontSize: "0.82rem",
  fontFamily: "var(--font-body)",
  background: "#fff",
  color: "var(--color-text)",
  cursor: "pointer",
};

const primaryBtn: React.CSSProperties = {
  background: "var(--color-burgundy)",
  border: "none",
  color: "#fff",
  padding: "0.45rem 1rem",
  borderRadius: "8px",
  fontSize: "0.8rem",
  cursor: "pointer",
  fontFamily: "var(--font-body)",
  fontWeight: 600,
  display: "inline-flex",
  alignItems: "center",
};

const ghostBtn: React.CSSProperties = {
  background: "var(--color-cream)",
  border: "1px solid var(--color-border)",
  color: "var(--color-text-dim)",
  padding: "0.4rem 0.9rem",
  borderRadius: "8px",
  fontSize: "0.78rem",
  cursor: "pointer",
  fontFamily: "var(--font-body)",
  display: "inline-flex",
  alignItems: "center",
};

function StatusPill({ status }: { status: DraftStatus }) {
  const map: Record<DraftStatus, { bg: string; color: string; label: string }> = {
    draft: { bg: "var(--color-cream)", color: "var(--color-taupe)", label: "Draft" },
    scheduled: { bg: "var(--color-burgundy-soft, #fdf0f0)", color: "var(--color-burgundy)", label: "Scheduled" },
    posted: { bg: "var(--color-cream)", color: "var(--color-text-dim)", label: "Posted" },
  };
  const s = map[status];
  return (
    <span
      style={{
        background: s.bg,
        color: s.color,
        padding: "0.18rem 0.6rem",
        borderRadius: "20px",
        fontSize: "0.7rem",
        fontWeight: 700,
        letterSpacing: "0.04em",
      }}
    >
      {s.label}
    </span>
  );
}

function Tag({
  children,
  tone = "default",
}: {
  children: React.ReactNode;
  tone?: "default" | "dim" | "burgundy";
}) {
  const styles =
    tone === "burgundy"
      ? { bg: "var(--color-burgundy-soft, #fdf0f0)", color: "var(--color-burgundy)" }
      : tone === "dim"
      ? { bg: "var(--color-cream)", color: "var(--color-text-dim)" }
      : { bg: "var(--color-cream)", color: "var(--color-taupe)" };
  return (
    <span
      style={{
        fontSize: "0.66rem",
        background: styles.bg,
        color: styles.color,
        padding: "0.12rem 0.55rem",
        borderRadius: "20px",
        fontWeight: 600,
        letterSpacing: "0.04em",
      }}
    >
      {children}
    </span>
  );
}
