"use client";
import { useEffect, useMemo, useState } from "react";
import { Plus, Copy, Check, Trash2, List, Calendar as CalendarIcon, ChevronLeft, ChevronRight, AlertCircle } from "lucide-react";
import TabContainer from "../shared/TabContainer";
import TabHeader from "../shared/TabHeader";
import EmptyState from "../shared/EmptyState";
import PasteFromClaude, { stripCodeFences } from "../shared/PasteFromClaude";
import CopyPromptButton, { FatPromptPreview } from "../shared/CopyPromptButton";
import {
  buildDraftCaptionPrompt,
  buildCarouselPrompt,
  buildFreshHooksPrompt,
  buildStoryPrompt,
  buildReelPrompt,
} from "../../../lib/promptBuilders";
import { fetchEffectiveSettings, type TriggerTriplet } from "../../../lib/settings";

type DraftStatus = "draft" | "scheduled" | "posted";

type Draft = {
  id: string;
  hook: string;
  caption: string;
  trigger_word: string | null;
  slide_count: number;
  type: "carousel" | "reel" | "image" | "story";
  status: DraftStatus;
  scheduled_for: string | null;
  posted_at: string | null;
  pillar?: string | null;
  created_at: string;
  updated_at: string;
};

type NewDraft = Omit<Draft, "id" | "created_at" | "updated_at" | "posted_at">;

type ViewMode = "list" | "calendar";

const TYPE_OPTIONS: Draft["type"][] = ["carousel", "reel", "image", "story"];

// Empty draft starts with NO trigger word selected. The Settings table is the
// source of truth (loaded async on mount) — defaulting to a hardcoded first
// trigger from config.json was a leak from the pre-Supabase shape. The user
// picks a trigger explicitly so the offer/topic/promise context block surfaces
// the linked offer/promise alongside it.
const emptyDraft = (): NewDraft => ({
  hook: "",
  caption: "",
  trigger_word: null,
  slide_count: 1,
  type: "carousel",
  status: "draft",
  scheduled_for: null,
});

/**
 * Drafts tab.
 *
 * Caption writer + status board.
 *  - Status flow: draft -> scheduled -> posted
 *  - Trigger word picker (drives lead-magnet tracking on IG)
 *  - Slide count (for carousels)
 *
 * Drafts can be written by hand, or generated by Claude: hit the "Draft a
 * caption with Claude" button, paste the prompt into claude.ai, paste the
 * 3-option reply back into the New draft form.
 */
export default function Drafts() {
  const [drafts, setDrafts] = useState<Draft[]>([]);
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [statusFilter, setStatusFilter] = useState<"all" | DraftStatus>("draft");
  const [view, setView] = useState<ViewMode>("list");
  const [weekOffset, setWeekOffset] = useState(0);

  const [addOpen, setAddOpen] = useState(false);
  const [draft, setDraft] = useState<NewDraft>(emptyDraft());

  const [copiedId, setCopiedId] = useState<string | null>(null);

  // Triggers come from the Settings tab (Supabase → localStorage → config),
  // not directly from config.json. The triplet shape lets us surface the
  // linked offer/topic/promise the moment a customer picks a trigger word
  // so they (and Claude, via buildDraftCaptionPrompt) keep the post on-topic
  // and the CTA grounded in the promise.
  const [triggers, setTriggers] = useState<TriggerTriplet[]>([]);
  useEffect(() => {
    let cancelled = false;
    fetchEffectiveSettings()
      .then((s) => {
        if (cancelled) return;
        setTriggers(s.trigger_words);
      })
      .catch(() => {
        if (!cancelled) setTriggers([]);
      });
    return () => {
      cancelled = true;
    };
  }, []);

  // Currently-selected triplet, surfaced under the dropdown as a writing
  // guidance block so the writer keeps the post on-topic and grounded in
  // the promise the reader will be told they're getting.
  const selectedTrigger = useMemo(
    () =>
      draft.trigger_word
        ? triggers.find((t) => t.word === draft.trigger_word) ?? null
        : null,
    [draft.trigger_word, triggers]
  );

  // Load drafts with an AbortController so a tab-switch (or hot-reload during
  // dev) doesn't trigger a "setState on unmounted component" warning, and
  // doesn't race a stale response into the freshly-mounted view. Strategy.tsx
  // already does this; Drafts was the last holdout.
  const load = (signal?: AbortSignal) => {
    setLoading(true);
    fetch("/api/data?tab=drafts", { signal })
      .then((r) => r.json())
      .then((r) => {
        if (signal?.aborted) return;
        setDrafts(r.data ?? []);
        setLoading(false);
      })
      .catch((e) => {
        // AbortError is normal on unmount; quietly drop it. Anything else
        // we let surface as "loading=false" so the empty state still renders
        // and the user isn't stuck on a spinner.
        if (e?.name === "AbortError") return;
        setLoading(false);
      });
  };

  useEffect(() => {
    const ctrl = new AbortController();
    load(ctrl.signal);
    return () => ctrl.abort();
  }, []);

  async function createDraft() {
    if (!draft.caption.trim()) return;
    setSaving(true);
    try {
      const res = await fetch("/api/data?tab=drafts", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(draft),
      });
      if (res.ok) {
        setDraft(emptyDraft());
        setAddOpen(false);
        load();
      }
    } finally {
      setSaving(false);
    }
  }

  async function patchDraft(id: string, patch: Partial<Draft>) {
    setSaving(true);
    try {
      const res = await fetch("/api/data?tab=drafts", {
        method: "PATCH",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ id, ...patch }),
      });
      if (res.ok) load();
    } finally {
      setSaving(false);
    }
  }

  async function deleteDraft(id: string) {
    if (!confirm("Delete this draft?")) return;
    setSaving(true);
    try {
      const res = await fetch(`/api/data?tab=drafts&id=${id}`, { method: "DELETE" });
      if (res.ok) load();
    } finally {
      setSaving(false);
    }
  }

  function copyCaption(d: Draft) {
    if (!navigator.clipboard) return;
    navigator.clipboard.writeText(d.caption).then(() => {
      setCopiedId(d.id);
      setTimeout(() => setCopiedId(null), 1500);
    });
  }

  const counts = useMemo(
    () => ({
      draft: drafts.filter((d) => d.status === "draft").length,
      scheduled: drafts.filter((d) => d.status === "scheduled").length,
      posted: drafts.filter((d) => d.status === "posted").length,
    }),
    [drafts]
  );

  const visible = statusFilter === "all" ? drafts : drafts.filter((d) => d.status === statusFilter);

  return (
    <TabContainer>
      <TabHeader
        title="Drafts"
        subtitle="Write captions in your voice. Tag with trigger words, set slide count, move them from draft to scheduled to posted."
        onScrapeComplete={load}
      />

      {/* Status filters + add button */}
      <div
        style={{
          display: "flex",
          justifyContent: "space-between",
          alignItems: "center",
          flexWrap: "wrap",
          gap: "0.6rem",
          marginBottom: "1.5rem",
        }}
      >
        <div style={{ display: "flex", gap: "0.35rem", flexWrap: "wrap" }}>
          {(["draft", "scheduled", "posted", "all"] as const).map((s) => {
            const active = statusFilter === s;
            const count = s === "all" ? drafts.length : counts[s];
            return (
              <button
                key={s}
                onClick={() => setStatusFilter(s)}
                style={{
                  background: active ? "var(--color-burgundy)" : "var(--color-cream)",
                  border: "none",
                  color: active ? "#fff" : "var(--color-text-dim)",
                  padding: "0.4rem 0.95rem",
                  borderRadius: "20px",
                  fontSize: "0.75rem",
                  cursor: "pointer",
                  fontFamily: "var(--font-body)",
                  fontWeight: 600,
                }}
              >
                {s === "all" ? `All (${count})` : `${cap(s)} (${count})`}
              </button>
            );
          })}
        </div>
        <div style={{ display: "inline-flex", gap: "0.45rem", alignItems: "center" }}>
          {/* View mode toggle */}
          <div
            style={{
              display: "inline-flex",
              background: "var(--color-cream)",
              borderRadius: "10px",
              padding: "0.2rem",
              gap: "0.15rem",
            }}
          >
            <ViewToggle
              active={view === "list"}
              onClick={() => setView("list")}
              icon={<List size={13} strokeWidth={2} />}
              label="List"
            />
            <ViewToggle
              active={view === "calendar"}
              onClick={() => setView("calendar")}
              icon={<CalendarIcon size={13} strokeWidth={2} />}
              label="Calendar"
            />
          </div>
          <button
            onClick={() => {
              if (addOpen) setAddOpen(false);
              else {
                setDraft(emptyDraft());
                setAddOpen(true);
              }
            }}
            style={{
              background: "var(--color-burgundy)",
              border: "none",
              color: "#fff",
              padding: "0.55rem 1.1rem",
              borderRadius: "10px",
              fontSize: "0.82rem",
              cursor: "pointer",
              fontFamily: "var(--font-body)",
              fontWeight: 600,
              display: "inline-flex",
              alignItems: "center",
              gap: "0.4rem",
            }}
          >
            <Plus size={14} strokeWidth={2.2} />
            {addOpen ? "Close" : "New draft"}
          </button>
        </div>
      </div>

      {/* Add form */}
      {addOpen && (
        <div
          style={{
            background: "#fff",
            border: "1px solid var(--color-burgundy)",
            borderRadius: "14px",
            padding: "1.25rem 1.5rem",
            marginBottom: "1.5rem",
            boxShadow: "var(--shadow-sm)",
          }}
        >
          <p
            style={{
              fontSize: "0.7rem",
              color: "var(--color-text-dim)",
              letterSpacing: "0.1em",
              textTransform: "uppercase",
              marginBottom: "0.85rem",
              fontWeight: 700,
            }}
          >
            New draft
          </p>

          {/* Visible fat prompt FIRST — the writer reads what would go into
              Claude before they decide to click the button. Thessa's UX
              note: "de prompt boven de claude knop, dat is de volgorde
              waarin ze ook werkt". So the prompt opens by default and the
              "Draft a caption with Claude" button sits underneath as the
              follow-up action. */}
          <div style={{ marginBottom: "0.6rem" }}>
            <FatPromptPreview
              buildPrompt={() => buildDraftCaptionPrompt("", selectedTrigger ?? undefined)}
              label="Show the full Claude prompt (read + copy)"
              defaultOpen
              cacheKey={selectedTrigger?.word ?? "none"}
            />
          </div>

          {/* Then the round-trip button. It copies the same fat prompt the
              customer just read above and opens claude.ai in a new tab.
              The PasteFromClaude widget below accepts the reply. */}
          <div style={{ marginBottom: "0.85rem", display: "flex", flexWrap: "wrap", gap: "0.5rem", alignItems: "center" }}>
            <CopyPromptButton
              label={
                selectedTrigger
                  ? `Draft a caption with Claude (using ${selectedTrigger.word})`
                  : "Draft a caption with Claude"
              }
              buildPrompt={() => buildDraftCaptionPrompt("", selectedTrigger ?? undefined)}
              tone="secondary"
            />
            <span style={{ fontSize: "0.7rem", color: "var(--color-text-dim)" }}>
              {selectedTrigger
                ? "Claude will write 3 captions on the linked topic, with the CTA grounded in the linked promise."
                : "Pick a trigger word above to ground the CTA in your linked offer/promise."}
            </span>
          </div>

          {/* Format-specific Claude buttons. Each one carries the framework
              for ONE Instagram surface (carousel slides, 10 fresh hooks for
              one topic, story arc, B-roll-or-voiceover reel script). The
              customer reads the "Draft a caption with Claude" prompt above
              and picks the format that matches what they're actually about
              to ship. Trigger word context flows into each (where relevant)
              so the CTA stays linked to the offer/promise. */}
          <div style={{ marginBottom: "0.85rem" }}>
            <p
              style={{
                fontSize: "0.7rem",
                color: "var(--color-text-dim)",
                letterSpacing: "0.08em",
                textTransform: "uppercase",
                marginBottom: "0.5rem",
                fontWeight: 700,
              }}
            >
              Or pick a format-specific prompt
            </p>
            <div style={{ display: "flex", flexWrap: "wrap", gap: "0.5rem", alignItems: "center" }}>
              <CopyPromptButton
                label="Carousel (slide-by-slide)"
                buildPrompt={() => buildCarouselPrompt("", selectedTrigger ?? undefined)}
                tone="secondary"
              />
              <CopyPromptButton
                label="10 fresh hooks for a topic"
                buildPrompt={() => buildFreshHooksPrompt("", "")}
                tone="secondary"
              />
              <CopyPromptButton
                label="Story sequence (1 to 4 slides)"
                buildPrompt={() => buildStoryPrompt("", selectedTrigger ?? undefined, "", "")}
                tone="secondary"
              />
              <CopyPromptButton
                label="Reel script (B-roll or voiceover)"
                buildPrompt={() => buildReelPrompt("", selectedTrigger ?? undefined, "")}
                tone="secondary"
              />
            </div>
            <span style={{ fontSize: "0.7rem", color: "var(--color-text-dim)", display: "block", marginTop: "0.45rem" }}>
              Each one builds a fat prompt with your voice rules + winners baked in. Paste into Claude, paste the reply back below, hit Apply.
            </span>
          </div>

          <PasteFromClaude<ParsedDraftOption[]>
            label="Paste Claude's 3 caption options"
            parse={parseDraftOptionsReply}
            render={(opts) => (
              <ol style={{ margin: 0, paddingLeft: "1.1rem", display: "grid", gap: "0.55rem" }}>
                {opts.map((o, i) => (
                  <li key={i} style={{ display: "grid", gap: "0.2rem" }}>
                    <strong style={{ fontFamily: "var(--font-header)" }}>{o.hook}</strong>
                    <span style={{ color: "var(--color-text-dim)", fontSize: "0.72rem" }}>
                      {o.format ?? "·"}
                    </span>
                  </li>
                ))}
              </ol>
            )}
            onApply={(opts) => {
              // First option populates the form by default — the customer
              // can scroll up after applying and edit. We assemble the
              // caption body as: BODY \n\n CTA so it lands in one textarea.
              const first = opts[0];
              if (!first) return;
              setDraft((d) => ({
                ...d,
                hook: first.hook,
                caption: first.cta ? `${first.body}\n\n${first.cta}` : first.body,
                slide_count:
                  first.format && first.format.toLowerCase().includes("carousel")
                    ? Number((first.format.match(/(\d+)/) ?? [])[1] ?? d.slide_count) || d.slide_count
                    : d.slide_count,
                type:
                  first.format && first.format.toLowerCase().includes("reel")
                    ? "reel"
                    : first.format && first.format.toLowerCase().includes("image")
                    ? "image"
                    : first.format && first.format.toLowerCase().includes("carousel")
                    ? "carousel"
                    : d.type,
              }));
            }}
          />

          <input
            type="text"
            value={draft.hook}
            onChange={(e) => setDraft({ ...draft, hook: e.target.value })}
            placeholder="Hook (first line, the thing that stops the scroll)"
            style={inputStyle}
          />

          <textarea
            value={draft.caption}
            onChange={(e) => setDraft({ ...draft, caption: e.target.value })}
            placeholder="Caption body. Write the scene, not a label."
            rows={6}
            style={{ ...inputStyle, resize: "vertical", marginTop: "0.5rem" }}
          />

          <div
            style={{
              display: "flex",
              gap: "0.5rem",
              marginTop: "0.75rem",
              flexWrap: "wrap",
              alignItems: "center",
            }}
          >
            <select
              value={draft.type}
              onChange={(e) => setDraft({ ...draft, type: e.target.value as Draft["type"] })}
              style={selectStyle}
            >
              {TYPE_OPTIONS.map((t) => (
                <option key={t} value={t}>
                  {cap(t)}
                </option>
              ))}
            </select>

            <select
              value={draft.slide_count}
              onChange={(e) => setDraft({ ...draft, slide_count: Number(e.target.value) })}
              style={selectStyle}
            >
              {[1, 2, 3, 4, 5, 6, 7, 8, 9, 10].map((n) => (
                <option key={n} value={n}>
                  {n} slide{n > 1 ? "s" : ""}
                </option>
              ))}
            </select>

            <select
              value={draft.trigger_word ?? ""}
              onChange={(e) => setDraft({ ...draft, trigger_word: e.target.value || null })}
              style={selectStyle}
            >
              <option value="">No trigger word</option>
              {triggers.map((t) => (
                <option key={t.word} value={t.word}>
                  {t.word}
                </option>
              ))}
            </select>
          </div>

          {/* Scheduled date+time. Optional on draft creation — if filled in,
              the draft saves with scheduled_for already populated so the
              writer can move straight from "write" to "scheduled" without a
              second click. The input value is the local datetime; we
              round-trip through a Date to get an ISO string for the API. */}
          <div
            style={{
              display: "flex",
              gap: "0.5rem",
              marginTop: "0.75rem",
              flexWrap: "wrap",
              alignItems: "center",
            }}
          >
            <label
              htmlFor="new-draft-schedule"
              style={{
                fontSize: "0.72rem",
                color: "var(--color-text-dim)",
                fontWeight: 600,
                letterSpacing: "0.04em",
              }}
            >
              Schedule for
            </label>
            <input
              id="new-draft-schedule"
              type="datetime-local"
              aria-label="Schedule new draft for date and time"
              value={draft.scheduled_for ? toLocalInput(draft.scheduled_for) : ""}
              onChange={(e) =>
                setDraft({
                  ...draft,
                  scheduled_for: e.target.value ? new Date(e.target.value).toISOString() : null,
                  // If we just set a date, flip status to scheduled so the calendar
                  // picks it up immediately on save. If we cleared it, drop back to draft.
                  status: e.target.value ? "scheduled" : "draft",
                })
              }
              style={selectStyle}
            />
            {draft.scheduled_for && (
              <button
                type="button"
                onClick={() =>
                  setDraft({ ...draft, scheduled_for: null, status: "draft" })
                }
                style={{
                  ...ghostBtn,
                  padding: "0.35rem 0.75rem",
                  fontSize: "0.72rem",
                }}
              >
                Clear date
              </button>
            )}
            <span style={{ fontSize: "0.7rem", color: "var(--color-text-dim)" }}>
              Optional — fill in to save straight to the calendar.
            </span>
          </div>

          {/* Trigger context block — surfaces the offer/topic/promise tied to
              the picked trigger so the writer keeps the post on-topic + the
              CTA grounded in the promise. The same triplet gets spliced into
              the Claude prompt below when "Draft with Claude" is hit, so what
              the writer sees here matches what Claude is asked to honour. */}
          {selectedTrigger && (
            <div
              style={{
                marginTop: "0.75rem",
                padding: "0.85rem 1rem",
                background: "var(--color-cream)",
                border: "1px solid var(--color-border)",
                borderRadius: "10px",
              }}
            >
              <p
                style={{
                  fontSize: "0.62rem",
                  letterSpacing: "0.12em",
                  textTransform: "uppercase",
                  color: "var(--color-taupe)",
                  fontWeight: 700,
                  margin: 0,
                  marginBottom: "0.5rem",
                }}
              >
                Trigger context — write to this
              </p>
              {!selectedTrigger.offer && !selectedTrigger.topic && !selectedTrigger.promise ? (
                <div
                  style={{
                    display: "flex",
                    gap: "0.45rem",
                    alignItems: "flex-start",
                    fontSize: "0.78rem",
                    color: "var(--color-burgundy)",
                  }}
                >
                  <AlertCircle size={14} strokeWidth={2} style={{ flexShrink: 0, marginTop: "0.1rem" }} />
                  <span>
                    No offer / topic / promise linked to <strong>{selectedTrigger.word}</strong> yet.
                    Open Settings → Trigger words to fill them in so the CTA can be grounded.
                  </span>
                </div>
              ) : (
                <div style={{ display: "grid", gap: "0.4rem", fontSize: "0.8rem", lineHeight: 1.45 }}>
                  <ContextRow label="Offer" value={selectedTrigger.offer} />
                  <ContextRow label="Topic" value={selectedTrigger.topic} />
                  <ContextRow label="Promise" value={selectedTrigger.promise} />
                </div>
              )}
            </div>
          )}

          <div style={{ display: "flex", gap: "0.5rem", marginTop: "1rem" }}>
            <button
              onClick={createDraft}
              disabled={saving || !draft.caption.trim()}
              style={{
                background: "var(--color-burgundy)",
                border: "none",
                color: "#fff",
                padding: "0.55rem 1.1rem",
                borderRadius: "8px",
                fontSize: "0.82rem",
                cursor: "pointer",
                fontFamily: "var(--font-body)",
                fontWeight: 600,
                opacity: saving || !draft.caption.trim() ? 0.6 : 1,
              }}
            >
              {saving ? "Saving..." : "Save draft"}
            </button>
            <button onClick={() => setAddOpen(false)} style={ghostBtn}>
              Cancel
            </button>
          </div>
        </div>
      )}

      {loading && (
        <div className="stagger" style={{ display: "flex", flexDirection: "column", gap: "0.6rem" }}>
          {[0, 1, 2].map((i) => (
            <div key={i} className="skeleton" style={{ height: "110px" }} />
          ))}
        </div>
      )}

      {!loading && drafts.length === 0 && (
        <EmptyState
          title="No drafts yet"
          body="Click below to copy a caption prompt pre-filled with your voice rules + top hooks + recent performance. claude.ai opens in a new tab. Paste, get 3 caption options, paste the one you like back here. Or skip Claude and write from scratch with the second button."
          claudePrompt={() => buildDraftCaptionPrompt("")}
          claudeButtonLabel="Draft a caption with Claude"
          actionLabel="Write one by hand"
          onAction={() => {
            setDraft(emptyDraft());
            setAddOpen(true);
          }}
        />
      )}

      {!loading && drafts.length > 0 && view === "list" && visible.length === 0 && (
        <div
          style={{
            background: "var(--color-cream)",
            border: "1px dashed var(--color-border)",
            borderRadius: "10px",
            padding: "1.5rem",
            textAlign: "center",
            fontSize: "0.85rem",
            color: "var(--color-text-dim)",
          }}
        >
          Nothing in {statusFilter}. Switch filter to see other drafts.
        </div>
      )}

      {!loading && drafts.length > 0 && view === "calendar" && (
        <CalendarView
          drafts={drafts}
          weekOffset={weekOffset}
          onShift={(delta) => setWeekOffset((w) => w + delta)}
          onReset={() => setWeekOffset(0)}
        />
      )}

      {view === "list" && (
      <div style={{ display: "flex", flexDirection: "column", gap: "0.75rem" }}>
        {visible.map((d) => (
          <div
            key={d.id}
            style={{
              background: "#fff",
              border: "1px solid var(--color-border)",
              borderRadius: "12px",
              padding: "1rem 1.25rem",
              boxShadow: "var(--shadow-sm)",
              opacity: d.status === "posted" ? 0.72 : 1,
            }}
          >
            <div style={{ display: "flex", gap: "0.4rem", marginBottom: "0.5rem", flexWrap: "wrap", alignItems: "center" }}>
              <StatusPill status={d.status} />
              <Tag>{d.type}</Tag>
              <Tag tone="dim">
                {d.slide_count} slide{d.slide_count > 1 ? "s" : ""}
              </Tag>
              {d.trigger_word && <Tag tone="burgundy">{d.trigger_word}</Tag>}
            </div>

            {d.hook && (
              <p style={{ fontFamily: "var(--font-header)", fontSize: "1.05rem", marginBottom: "0.45rem", lineHeight: 1.35 }}>
                {d.hook}
              </p>
            )}
            <p
              style={{
                fontSize: "0.86rem",
                lineHeight: 1.55,
                whiteSpace: "pre-wrap",
                color: "var(--color-text)",
                marginBottom: "0.85rem",
              }}
            >
              {d.caption}
            </p>

            <div style={{ display: "flex", gap: "0.5rem", flexWrap: "wrap", alignItems: "center" }}>
              {d.status === "draft" && (
                <ScheduleControl
                  draft={d}
                  saving={saving}
                  onSchedule={(iso) =>
                    patchDraft(d.id, { status: "scheduled", scheduled_for: iso })
                  }
                />
              )}
              {d.status === "scheduled" && (
                <RescheduleControl
                  draft={d}
                  saving={saving}
                  onReschedule={(iso) => patchDraft(d.id, { scheduled_for: iso })}
                />
              )}
              {d.status === "scheduled" && (
                <>
                  <button
                    onClick={() => patchDraft(d.id, { status: "posted" })}
                    style={primaryBtn}
                    disabled={saving}
                  >
                    <Check size={13} strokeWidth={2.2} style={{ marginRight: "0.3rem" }} />
                    Mark posted
                  </button>
                  <button onClick={() => patchDraft(d.id, { status: "draft" })} style={ghostBtn}>
                    Back to draft
                  </button>
                </>
              )}
              {d.status === "posted" && (
                <button onClick={() => patchDraft(d.id, { status: "draft" })} style={ghostBtn}>
                  Reopen
                </button>
              )}
              <button onClick={() => copyCaption(d)} style={ghostBtn}>
                <Copy size={12} strokeWidth={1.8} style={{ marginRight: "0.3rem" }} />
                {copiedId === d.id ? "Copied!" : "Copy"}
              </button>
              <button
                onClick={() => deleteDraft(d.id)}
                style={{ ...ghostBtn, color: "var(--color-burgundy)", marginLeft: "auto" }}
                aria-label="Delete draft"
                disabled={saving}
              >
                <Trash2 size={12} strokeWidth={1.8} />
              </button>
            </div>
          </div>
        ))}
      </div>
      )}

      {drafts.length > 0 && (
        <p
          style={{
            marginTop: "2rem",
            fontSize: "0.72rem",
            color: "var(--color-text-dim)",
            textAlign: "center",
          }}
        >
          Need a fresh caption? Hit{" "}
          <strong style={{ color: "var(--color-burgundy)" }}>New draft</strong>{" "}
          and paste a Claude reply, or write one from scratch.
        </p>
      )}
    </TabContainer>
  );
}

function cap(s: string) {
  return s.charAt(0).toUpperCase() + s.slice(1);
}

function ContextRow({ label, value }: { label: string; value: string }) {
  // One row of the "Trigger context" panel. Blank values render as a soft
  // "not set" so the writer can see at a glance which leg of the triplet
  // is still empty without having to open Settings to check.
  const empty = !value || !value.trim();
  return (
    <div style={{ display: "grid", gridTemplateColumns: "5rem 1fr", gap: "0.6rem", alignItems: "baseline" }}>
      <span
        style={{
          fontSize: "0.66rem",
          letterSpacing: "0.08em",
          textTransform: "uppercase",
          color: "var(--color-text-dim)",
          fontWeight: 600,
        }}
      >
        {label}
      </span>
      <span style={{ color: empty ? "var(--color-text-dim)" : "var(--color-text)", fontStyle: empty ? "italic" : "normal" }}>
        {empty ? "not set" : value}
      </span>
    </div>
  );
}

const inputStyle: React.CSSProperties = {
  width: "100%",
  padding: "0.7rem 0.95rem",
  border: "1px solid var(--color-border)",
  borderRadius: "8px",
  fontSize: "0.88rem",
  fontFamily: "var(--font-body)",
  background: "#fff",
  color: "var(--color-text)",
  boxSizing: "border-box",
  outline: "none",
};

const selectStyle: React.CSSProperties = {
  padding: "0.5rem 0.85rem",
  border: "1px solid var(--color-border)",
  borderRadius: "8px",
  fontSize: "0.82rem",
  fontFamily: "var(--font-body)",
  background: "#fff",
  color: "var(--color-text)",
  cursor: "pointer",
};

const primaryBtn: React.CSSProperties = {
  background: "var(--color-burgundy)",
  border: "none",
  color: "#fff",
  padding: "0.45rem 1rem",
  borderRadius: "8px",
  fontSize: "0.8rem",
  cursor: "pointer",
  fontFamily: "var(--font-body)",
  fontWeight: 600,
  display: "inline-flex",
  alignItems: "center",
};

const ghostBtn: React.CSSProperties = {
  background: "var(--color-cream)",
  border: "1px solid var(--color-border)",
  color: "var(--color-text-dim)",
  padding: "0.4rem 0.9rem",
  borderRadius: "8px",
  fontSize: "0.78rem",
  cursor: "pointer",
  fontFamily: "var(--font-body)",
  display: "inline-flex",
  alignItems: "center",
};

function StatusPill({ status }: { status: DraftStatus }) {
  const map: Record<DraftStatus, { bg: string; color: string; label: string }> = {
    draft: { bg: "var(--color-cream)", color: "var(--color-taupe)", label: "Draft" },
    scheduled: { bg: "var(--color-burgundy-soft, #fdf0f0)", color: "var(--color-burgundy)", label: "Scheduled" },
    posted: { bg: "var(--color-cream)", color: "var(--color-text-dim)", label: "Posted" },
  };
  const s = map[status];
  return (
    <span
      style={{
        background: s.bg,
        color: s.color,
        padding: "0.18rem 0.6rem",
        borderRadius: "20px",
        fontSize: "0.7rem",
        fontWeight: 700,
        letterSpacing: "0.04em",
      }}
    >
      {s.label}
    </span>
  );
}

function ViewToggle({
  active,
  onClick,
  icon,
  label,
}: {
  active: boolean;
  onClick: () => void;
  icon: React.ReactNode;
  label: string;
}) {
  return (
    <button
      type="button"
      onClick={onClick}
      style={{
        display: "inline-flex",
        alignItems: "center",
        gap: "0.35rem",
        background: active ? "#fff" : "transparent",
        border: "none",
        color: active ? "var(--color-burgundy)" : "var(--color-text-dim)",
        padding: "0.35rem 0.7rem",
        borderRadius: "8px",
        fontSize: "0.74rem",
        fontWeight: 600,
        cursor: "pointer",
        fontFamily: "var(--font-body)",
        boxShadow: active ? "var(--shadow-sm)" : "none",
      }}
    >
      {icon}
      {label}
    </button>
  );
}

/* ─────────── Calendar week-grid view ─────────── */

function CalendarView({
  drafts,
  weekOffset,
  onShift,
  onReset,
}: {
  drafts: Draft[];
  weekOffset: number;
  onShift: (delta: number) => void;
  onReset: () => void;
}) {
  // Monday-start week. We bucket every draft with a scheduled_for into the
  // matching day cell; unscheduled drafts go into the "Inbox" rail on the
  // left so they're never invisible.
  const today = new Date();
  const weekStart = startOfWeek(today, weekOffset);
  const days = Array.from({ length: 7 }, (_, i) => {
    const d = new Date(weekStart);
    d.setDate(weekStart.getDate() + i);
    return d;
  });

  const scheduled = drafts.filter((d) => !!d.scheduled_for);
  const byDay = new Map<string, Draft[]>();
  for (const d of scheduled) {
    const key = ymd(new Date(d.scheduled_for!));
    if (!byDay.has(key)) byDay.set(key, []);
    byDay.get(key)!.push(d);
  }

  const unscheduled = drafts.filter((d) => !d.scheduled_for && d.status !== "posted").slice(0, 12);

  const fmtWeek = `${days[0].toLocaleDateString("en-GB", { day: "numeric", month: "short" })} – ${days[6].toLocaleDateString("en-GB", { day: "numeric", month: "short" })}`;

  return (
    <div>
      {/* Week nav */}
      <div
        style={{
          display: "flex",
          alignItems: "center",
          gap: "0.6rem",
          marginBottom: "0.85rem",
        }}
      >
        <button onClick={() => onShift(-1)} style={navBtn} aria-label="Previous week">
          <ChevronLeft size={14} strokeWidth={2} />
        </button>
        <span
          style={{
            fontFamily: "var(--font-header)",
            fontSize: "1rem",
            color: "var(--color-text)",
            minWidth: "10rem",
            textAlign: "center",
          }}
        >
          {fmtWeek}
        </span>
        <button onClick={() => onShift(1)} style={navBtn} aria-label="Next week">
          <ChevronRight size={14} strokeWidth={2} />
        </button>
        {weekOffset !== 0 && (
          <button
            onClick={onReset}
            style={{
              ...navBtn,
              width: "auto",
              padding: "0 0.7rem",
              fontSize: "0.72rem",
            }}
          >
            This week
          </button>
        )}
      </div>

      {/* Grid: 7 day columns + inbox rail */}
      <div
        style={{
          display: "grid",
          gridTemplateColumns: "1fr",
          gap: "0.6rem",
        }}
      >
        <div
          style={{
            display: "grid",
            gridTemplateColumns: "minmax(140px, 0.9fr) repeat(7, minmax(120px, 1fr))",
            gap: "0.5rem",
          }}
          className="cal-grid"
        >
          {/* Inbox rail */}
          <div
            style={{
              background: "var(--color-cream)",
              border: "1px dashed var(--color-border)",
              borderRadius: "10px",
              padding: "0.6rem 0.7rem",
              minHeight: "180px",
            }}
          >
            <p
              style={{
                fontSize: "0.62rem",
                letterSpacing: "0.12em",
                textTransform: "uppercase",
                color: "var(--color-taupe)",
                fontWeight: 700,
                marginBottom: "0.5rem",
              }}
            >
              Inbox
            </p>
            {unscheduled.length === 0 ? (
              <p style={{ fontSize: "0.72rem", color: "var(--color-text-dim)" }}>
                Drafts with no scheduled date land here.
              </p>
            ) : (
              <div style={{ display: "flex", flexDirection: "column", gap: "0.35rem" }}>
                {unscheduled.map((d) => (
                  <CalendarCard key={d.id} draft={d} compact />
                ))}
              </div>
            )}
          </div>

          {days.map((d) => {
            const key = ymd(d);
            const items = byDay.get(key) ?? [];
            const isToday = ymd(today) === key;
            return (
              <div
                key={key}
                style={{
                  background: "#fff",
                  border: `1px solid ${isToday ? "var(--color-burgundy)" : "var(--color-border)"}`,
                  borderRadius: "10px",
                  padding: "0.6rem 0.7rem",
                  minHeight: "180px",
                }}
              >
                <p
                  style={{
                    fontSize: "0.62rem",
                    letterSpacing: "0.1em",
                    textTransform: "uppercase",
                    color: isToday ? "var(--color-burgundy)" : "var(--color-text-dim)",
                    fontWeight: 700,
                    marginBottom: "0.1rem",
                  }}
                >
                  {d.toLocaleDateString("en-GB", { weekday: "short" })}
                </p>
                <p
                  style={{
                    fontFamily: "var(--font-header)",
                    fontSize: "1.05rem",
                    color: isToday ? "var(--color-burgundy)" : "var(--color-text)",
                    marginBottom: "0.55rem",
                  }}
                >
                  {d.getDate()}
                </p>
                {items.length === 0 ? (
                  <p style={{ fontSize: "0.7rem", color: "var(--color-text-dim)", opacity: 0.7 }}>·</p>
                ) : (
                  <div style={{ display: "flex", flexDirection: "column", gap: "0.35rem" }}>
                    {items.map((it) => (
                      <CalendarCard key={it.id} draft={it} compact />
                    ))}
                  </div>
                )}
              </div>
            );
          })}
        </div>
      </div>

      <style jsx>{`
        @media (max-width: 900px) {
          :global(.cal-grid) {
            grid-template-columns: 1fr !important;
          }
        }
      `}</style>
    </div>
  );
}

function CalendarCard({ draft, compact }: { draft: Draft; compact?: boolean }) {
  const pillarColor = draft.pillar ? colorForPillar(draft.pillar) : "var(--color-taupe)";
  return (
    <div
      title={draft.caption.slice(0, 200)}
      style={{
        background: "#fff",
        border: "1px solid var(--color-border)",
        borderLeft: `3px solid ${pillarColor}`,
        borderRadius: "8px",
        padding: compact ? "0.4rem 0.55rem" : "0.6rem 0.75rem",
        fontSize: compact ? "0.74rem" : "0.82rem",
        lineHeight: 1.35,
        color: "var(--color-text)",
        cursor: "default",
      }}
    >
      <div
        style={{
          display: "flex",
          gap: "0.3rem",
          marginBottom: "0.2rem",
          alignItems: "center",
        }}
      >
        <span
          style={{
            fontSize: "0.6rem",
            background: "var(--color-cream)",
            color: "var(--color-taupe)",
            padding: "0.05rem 0.4rem",
            borderRadius: "20px",
            fontWeight: 700,
            letterSpacing: "0.04em",
            textTransform: "uppercase",
          }}
        >
          {draft.type}
        </span>
        {draft.pillar && (
          <span
            style={{
              fontSize: "0.6rem",
              color: pillarColor,
              fontWeight: 600,
            }}
          >
            {draft.pillar}
          </span>
        )}
      </div>
      <p
        style={{
          margin: 0,
          fontWeight: 600,
          overflow: "hidden",
          display: "-webkit-box",
          WebkitLineClamp: 2,
          WebkitBoxOrient: "vertical",
        }}
      >
        {draft.hook || draft.caption.slice(0, 60)}
      </p>
    </div>
  );
}

function startOfWeek(d: Date, weekOffset = 0): Date {
  const x = new Date(d);
  x.setHours(0, 0, 0, 0);
  // Monday-start: getDay() returns 0=Sun..6=Sat; we want Mon=0.
  const day = (x.getDay() + 6) % 7;
  x.setDate(x.getDate() - day + weekOffset * 7);
  return x;
}

function ymd(d: Date): string {
  return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}-${String(d.getDate()).padStart(2, "0")}`;
}

/**
 * Deterministic pastel color per pillar — same pillar name always gets the
 * same color across re-renders + sessions, no DB needed.
 */
function colorForPillar(name: string): string {
  let hash = 0;
  for (let i = 0; i < name.length; i++) hash = (hash * 31 + name.charCodeAt(i)) >>> 0;
  const hue = hash % 360;
  return `hsl(${hue}, 45%, 42%)`;
}

const navBtn: React.CSSProperties = {
  width: "32px",
  height: "32px",
  borderRadius: "8px",
  background: "#fff",
  border: "1px solid var(--color-border)",
  color: "var(--color-text)",
  cursor: "pointer",
  display: "inline-flex",
  alignItems: "center",
  justifyContent: "center",
  fontFamily: "var(--font-body)",
};

function Tag({
  children,
  tone = "default",
}: {
  children: React.ReactNode;
  tone?: "default" | "dim" | "burgundy";
}) {
  const styles =
    tone === "burgundy"
      ? { bg: "var(--color-burgundy-soft, #fdf0f0)", color: "var(--color-burgundy)" }
      : tone === "dim"
      ? { bg: "var(--color-cream)", color: "var(--color-text-dim)" }
      : { bg: "var(--color-cream)", color: "var(--color-taupe)" };
  return (
    <span
      style={{
        fontSize: "0.66rem",
        background: styles.bg,
        color: styles.color,
        padding: "0.12rem 0.55rem",
        borderRadius: "20px",
        fontWeight: 600,
        letterSpacing: "0.04em",
      }}
    >
      {children}
    </span>
  );
}

/* ─────────── Claude reply parser (caption options) ─────────── */

type ParsedDraftOption = {
  hook: string;
  body: string;
  cta?: string;
  format?: string;
};

/**
 * parseDraftOptionsReply.
 *
 * Claude returns Markdown with 3 numbered options. Each option includes a
 * Hook line, Body paragraphs, a CTA line, and a Format suggestion. The
 * exact layout the prompt asks for is:
 *
 *   1. Option 1
 *   - **Hook** — text...
 *   - **Body** — text...
 *   - **CTA** — text...
 *   - **Format** — text...
 *
 * Claude's Markdown rendering varies — sometimes it uses headings, sometimes
 * bullets, sometimes bold labels. This parser tolerates the common shapes
 * and returns up to 3 ParsedDraftOption objects. Empty result -> error.
 */
function parseDraftOptionsReply(
  raw: string
): { ok: true; value: ParsedDraftOption[] } | { ok: false; error: string } {
  const body = stripCodeFences(raw);
  // Split into option blocks. Look for "Option N" / "## N" / "**Option N**" /
  // "N." at the start of a line. Fall back to splitting on horizontal rules.
  const blocks = body
    .split(/^\s*(?:#{1,3}\s*)?(?:\*\*\s*)?(?:Option\s+)?\d+[.):]\s*(?:\*\*\s*)?/gim)
    .map((b) => b.trim())
    .filter((b) => b.length > 0);

  // Field-extraction regexes. The separator character class accepts colon,
  // hyphen, and U+2014 em-dash (—) because Claude occasionally emits
  // them between label and value even when we ask for plain colons. We use
  // the Unicode escape rather than a literal so this file stays em-dash-free
  // in source. The construction is split out so the character class is
  // defined once and reused for clarity.
  const sep = "[:\\-\\u2014]";
  const options: ParsedDraftOption[] = [];
  for (const block of blocks) {
    const hook = extractField(block, new RegExp(`(?:^|\\n)\\s*[-*]?\\s*\\*?\\*?Hook\\*?\\*?\\s*${sep}\\s*(.+?)(?=\\n\\s*[-*]?\\s*\\*?\\*?(?:Body|CTA|Format)|\\n\\n|$)`, "is"));
    const bodyText = extractField(block, new RegExp(`(?:^|\\n)\\s*[-*]?\\s*\\*?\\*?Body\\*?\\*?\\s*${sep}\\s*([\\s\\S]+?)(?=\\n\\s*[-*]?\\s*\\*?\\*?(?:CTA|Format)|$)`, "is"));
    const cta = extractField(block, new RegExp(`(?:^|\\n)\\s*[-*]?\\s*\\*?\\*?CTA\\*?\\*?\\s*${sep}\\s*(.+?)(?=\\n\\s*[-*]?\\s*\\*?\\*?Format|\\n\\n|$)`, "is"));
    const format = extractField(block, new RegExp(`(?:^|\\n)\\s*[-*]?\\s*\\*?\\*?Format\\*?\\*?\\s*${sep}\\s*(.+?)(?=\\n\\n|$)`, "is"));
    if (hook || bodyText) {
      options.push({
        hook: cleanLine(hook ?? ""),
        body: cleanLine(bodyText ?? ""),
        cta: cta ? cleanLine(cta) : undefined,
        format: format ? cleanLine(format) : undefined,
      });
    }
    if (options.length === 3) break;
  }

  if (options.length === 0) {
    return {
      ok: false,
      error:
        "Could not find Hook/Body/CTA/Format labels in the reply. Make sure you copied Claude's full reply with all 3 options.",
    };
  }
  return { ok: true, value: options };
}

function extractField(text: string, re: RegExp): string | null {
  const m = text.match(re);
  return m && m[1] ? m[1].trim() : null;
}

function cleanLine(s: string): string {
  return s
    .replace(/^\*\*|\*\*$/g, "")
    .replace(/^["'`]|["'`]$/g, "")
    .trim();
}

/**
 * Convert an ISO timestamp to the `YYYY-MM-DDTHH:MM` local-time string that
 * <input type="datetime-local"> expects. Browsers refuse anything else, and
 * passing an ISO directly leaves the input empty without explanation.
 */
function toLocalInput(iso: string): string {
  const d = new Date(iso);
  if (isNaN(d.getTime())) return "";
  const pad = (n: number) => String(n).padStart(2, "0");
  return `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())}T${pad(d.getHours())}:${pad(d.getMinutes())}`;
}

/**
 * ScheduleControl — sits on a card whose status is "draft". Customer picks
 * a date+time, then hits Schedule, and the draft moves to status=scheduled
 * with scheduled_for filled in (one PATCH, no second click). Before this
 * existed, the Schedule button just flipped status with no date — drafts
 * went to "scheduled" but never showed up on the calendar.
 */
function ScheduleControl({
  draft,
  saving,
  onSchedule,
}: {
  draft: Draft;
  saving: boolean;
  onSchedule: (iso: string) => void;
}) {
  const [when, setWhen] = useState<string>(() =>
    draft.scheduled_for ? toLocalInput(draft.scheduled_for) : ""
  );
  // Re-sync local input value if the parent's scheduled_for changes underneath
  // (e.g. external patch arrived while the component instance was reused).
  // Without this, useState's initializer only runs once per mount, so the
  // displayed date could go stale.
  useEffect(() => {
    setWhen(draft.scheduled_for ? toLocalInput(draft.scheduled_for) : "");
  }, [draft.scheduled_for]);
  return (
    <div style={{ display: "inline-flex", gap: "0.4rem", alignItems: "center", flexWrap: "wrap" }}>
      <input
        type="datetime-local"
        value={when}
        onChange={(e) => setWhen(e.target.value)}
        aria-label="Schedule date and time"
        style={{
          ...selectStyle,
          padding: "0.4rem 0.7rem",
          fontSize: "0.78rem",
        }}
      />
      <button
        type="button"
        onClick={() => {
          if (!when) return;
          onSchedule(new Date(when).toISOString());
        }}
        style={primaryBtn}
        disabled={saving || !when}
      >
        Schedule
      </button>
    </div>
  );
}

/**
 * RescheduleControl — same shape, but for drafts already in "scheduled"
 * status. Lets the customer move a scheduled draft to a new date without
 * having to send it back to "draft" first.
 */
function RescheduleControl({
  draft,
  saving,
  onReschedule,
}: {
  draft: Draft;
  saving: boolean;
  onReschedule: (iso: string) => void;
}) {
  const [when, setWhen] = useState<string>(() =>
    draft.scheduled_for ? toLocalInput(draft.scheduled_for) : ""
  );
  // Sync the local input with the prop when the parent's scheduled_for changes
  // — same reasoning as ScheduleControl above. After a successful reschedule,
  // the new prop value flows in and "changed" goes back to falsy on its own.
  useEffect(() => {
    setWhen(draft.scheduled_for ? toLocalInput(draft.scheduled_for) : "");
  }, [draft.scheduled_for]);
  const changed = when && draft.scheduled_for && when !== toLocalInput(draft.scheduled_for);
  return (
    <div style={{ display: "inline-flex", gap: "0.4rem", alignItems: "center", flexWrap: "wrap" }}>
      <input
        type="datetime-local"
        value={when}
        onChange={(e) => setWhen(e.target.value)}
        aria-label="Reschedule date and time"
        style={{
          ...selectStyle,
          padding: "0.4rem 0.7rem",
          fontSize: "0.78rem",
        }}
      />
      {changed && (
        <button
          type="button"
          onClick={() => {
            if (!when) return;
            onReschedule(new Date(when).toISOString());
          }}
          style={primaryBtn}
          disabled={saving || !when}
        >
          Reschedule
        </button>
      )}
    </div>
  );
}
